### ISSUE TITLE
how to solve this github.com/atomicals-go/atomicals-indexer/atomicals-core/witness/python-parse: cannot find module providing package

### ISSUE THREAD

**Issue by michaelHoxxxxxxx** [atomicals-community/atomicals-go#2]
[solve](go: finding module for package github.com/atomicals-go/atomicals-indexer/atomicals-core/witness/python-parse)

**Comment by 0xfakeSpike** [comment]
oh,my fault, pull latest code plz

**Comment by michaelHoxxxxxxx** [comment]
Thanks, the problem has been solved, however, I cannot find the "init" file in the "repo" file, which prevents me from "go run ./"

**Comment by TheHeBoy** [comment]
me too and I can't find conf/config.json.

**Comment by 0xfakeSpike** [comment]
i pushed init.go and json file again

**Comment by 0xfakeSpike** [comment]
> me too and I can't find conf/config.json.

hey anchor, 我记得你曾经回复过我的推特。如果你想参与进来，我觉得你可以看下atomicals-api服务。这个服务接口还很单一，你可以根据自己的想法添加更多新的接口，这样可以熟悉服务的sql表字段。
另外，为了避免btc链分叉的影响，api服务需要承担部分区块的atomicals交易处理工作。这部分逻辑的实现并不优雅，我也希望更多人和我讨论，看看有没有什么更好的方案

**Comment by michaelHoxxxxxxx** [comment]
When I "go run ./" in "atomical-api" it returns "Error: Configuration file etc/main-api.yaml, field 'btc_rpc_user' not set" and then I found the parameters of "main.go" for "atomicalsConfigFilePath", however, I couldn't find the path in the "atomicals-api" file, so, I copied the "conf" of the "atomical-indexer" file to this, but it still doesn't work, please help me

**Comment by 0xfakeSpike** [comment]
hey michael, thx for trying, these are indeed my negligence, I'm used to running code locally, but I didn't double-check the correctness of the uploaded code.  i have pushed again. but i suggest u run atomicals-indexer first, until atomicals-indexer catching latest btc block, atomicals-api service won't start, it will panic.
i u have any question just comment here

**Comment by michaelHoxxxxxxx** [comment]
You're welcome, the program is already running, however, I don't know if the atomic indexer gets new Bitcoin blocks, I checked my database and there is nothing there

**Comment by 0xfakeSpike** [comment]
u can check log or atomicals_tx table, it record all atomicals transactions. 
the first atomiclas tx will be catched on blockheight=808081, "atom" ft was deployed. u can see it in atomicals_global_distributed_ft table.
and from 808513, atom fts ware minted. form 808080 to 808513, it do need some time. when it catched 808513 u can see atom amount in atomicals_utxo_ft table.

by the way, in the latest version, i only catch dft and dmt operation, which indicat deploy ft asset and mint ft asset. because i have to implement payment model. if anyone want to take part in, connect me plz.
